// <auto-generated />
using auto_reg.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace autoreg.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171024081828_SeedEmployeeAttendances")]
    partial class SeedEmployeeAttendances
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("auto_reg.Core.Models.EmployeeAttendance", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<DateTime?>("AttendTime");

                    b.Property<string>("CompanyOffice")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool?>("IsAttend");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhotoFilename")
                        .HasMaxLength(100);

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("EmployeeAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
